######################################################################
# Automatically generated by qmake (3.0) Tue Dec 8 02:33:38 2015
######################################################################

TEMPLATE = app
TARGET = src
QT += core gui
QT += widgets
INCLUDEPATH += .

# Input
SOURCES += main.cpp main_window.cpp qnode.cpp
