######################################################################
# Automatically generated by qmake (3.0) Mon Nov 23 12:11:07 2015
######################################################################

TEMPLATE = app
TARGET = QtHelloWorld
QT += core gui
QT += widgets
INCLUDEPATH += .

# Input
SOURCES += main.cpp
