set(_CATKIN_CURRENT_PACKAGE "Qt_ROS1")
set(Qt_ROS1_MAINTAINER "MERG <MERG@gmail.com>")
set(Qt_ROS1_DEPRECATED "")
set(Qt_ROS1_VERSION "0.1.0")
set(Qt_ROS1_BUILD_DEPENDS "qt_build" "roscpp" "rospy" "libqt4-dev")
set(Qt_ROS1_RUN_DEPENDS "qt_build" "roscpp" "rospy" "libqt4-dev")
set(Qt_ROS1_BUILDTOOL_DEPENDS "catkin")